[package]
name = "kubeweft-filesystem-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kubeweft-filesystem = { path = "../kubeweft-filesystem" }
kubeweft-model = { path = "../kubeweft-model" }
kubeweft-transport = { path = "../kubeweft-transport" }
